//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadFortalecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadFortalecimiento()
        {
            this.AutorXActividadFortalecimientoes = new HashSet<AutorXActividadFortalecimiento>();
            this.DocumentoActividadFortalecimientoes = new HashSet<DocumentoActividadFortalecimiento>();
            this.PersonaXActividadFortalecimientoes = new HashSet<PersonaXActividadFortalecimiento>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXActividadFortalecimiento> AutorXActividadFortalecimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoActividadFortalecimiento> DocumentoActividadFortalecimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXActividadFortalecimiento> PersonaXActividadFortalecimientoes { get; set; }
    }
}
