//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadFortalecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadFortalecimiento()
        {
            this.AutorXActividadFortalecimientoes = new HashSet<AutorXActividadFortalecimiento>();
            this.DocumentoActividadFortalecimientoes = new HashSet<DocumentoActividadFortalecimiento>();
            this.PersonaXActividadFortalecimientoes = new HashSet<PersonaXActividadFortalecimiento>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXActividadFortalecimiento> AutorXActividadFortalecimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoActividadFortalecimiento> DocumentoActividadFortalecimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXActividadFortalecimiento> PersonaXActividadFortalecimientoes { get; set; }
    }
}
