//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorXObraDidactica
    {
        public int ID { get; set; }
        public int id_autor { get; set; }
        public int id_obra_didactica { get; set; }
        public decimal distribucionAutoria { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual ObraDidactica ObraDidactica { get; set; }
    }
}
