//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autor()
        {
            this.AutorXActividadFortalecimientoes = new HashSet<AutorXActividadFortalecimiento>();
            this.AutorXArticuloes = new HashSet<AutorXArticulo>();
            this.AutorXCapituloes = new HashSet<AutorXCapitulo>();
            this.AutorXColaboracionEventoes = new HashSet<AutorXColaboracionEvento>();
            this.AutorXCursoCentroCapacitacions = new HashSet<AutorXCursoCentroCapacitacion>();
            this.AutorXDesarrolloSoftwares = new HashSet<AutorXDesarrolloSoftware>();
            this.AutorXObraAdministrativaDesarrolloes = new HashSet<AutorXObraAdministrativaDesarrollo>();
            this.AutorXObraArtisticas = new HashSet<AutorXObraArtistica>();
            this.AutorXObraDidacticas = new HashSet<AutorXObraDidactica>();
            this.AutorXOrganizacionEventoes = new HashSet<AutorXOrganizacionEvento>();
            this.AutorXOtraObraProfesionals = new HashSet<AutorXOtraObraProfesional>();
            this.AutorXParticipacionDeportivas = new HashSet<AutorXParticipacionDeportiva>();
            this.AutorXParticipacionDestacadas = new HashSet<AutorXParticipacionDestacada>();
            this.AutorXPatentes = new HashSet<AutorXPatente>();
            this.AutorXPonenciaCongresoes = new HashSet<AutorXPonenciaCongreso>();
            this.AutorXProyectoGraduacions = new HashSet<AutorXProyectoGraduacion>();
            this.AutorXProyectoInvestigacions = new HashSet<AutorXProyectoInvestigacion>();
            this.AutorXPublicacions = new HashSet<AutorXPublicacion>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string correoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXActividadFortalecimiento> AutorXActividadFortalecimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXArticulo> AutorXArticuloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXCapitulo> AutorXCapituloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXColaboracionEvento> AutorXColaboracionEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXCursoCentroCapacitacion> AutorXCursoCentroCapacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXDesarrolloSoftware> AutorXDesarrolloSoftwares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraAdministrativaDesarrollo> AutorXObraAdministrativaDesarrolloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraArtistica> AutorXObraArtisticas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraDidactica> AutorXObraDidacticas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXOrganizacionEvento> AutorXOrganizacionEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXOtraObraProfesional> AutorXOtraObraProfesionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDeportiva> AutorXParticipacionDeportivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDestacada> AutorXParticipacionDestacadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPatente> AutorXPatentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPonenciaCongreso> AutorXPonenciaCongresoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXProyectoGraduacion> AutorXProyectoGraduacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXProyectoInvestigacion> AutorXProyectoInvestigacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPublicacion> AutorXPublicacions { get; set; }
    }
}
