//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaboracionExterno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColaboracionExterno()
        {
            this.DocumentoColaboracionExternoes = new HashSet<DocumentoColaboracionExterno>();
            this.PersonaXColaboracionExternoes = new HashSet<PersonaXColaboracionExterno>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string anno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoColaboracionExterno> DocumentoColaboracionExternoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXColaboracionExterno> PersonaXColaboracionExternoes { get; set; }
    }
}
