//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaboracionEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColaboracionEvento()
        {
            this.AutorXColaboracionEventoes = new HashSet<AutorXColaboracionEvento>();
            this.DocumentoColaboracionEventoes = new HashSet<DocumentoColaboracionEvento>();
            this.PersonaXColaboracionEventoes = new HashSet<PersonaXColaboracionEvento>();
        }
    
        public int ID { get; set; }
        public string nombreEvento { get; set; }
        public string nombreEntidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXColaboracionEvento> AutorXColaboracionEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoColaboracionEvento> DocumentoColaboracionEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXColaboracionEvento> PersonaXColaboracionEventoes { get; set; }
    }
}
