//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoNoRemunerado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoNoRemunerado()
        {
            this.DocumentoCursoNoRemuneradoes = new HashSet<DocumentoCursoNoRemunerado>();
            this.PersonaXCursoNoRemuneradoes = new HashSet<PersonaXCursoNoRemunerado>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string periodoLectivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoCursoNoRemunerado> DocumentoCursoNoRemuneradoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCursoNoRemunerado> PersonaXCursoNoRemuneradoes { get; set; }
    }
}
