//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoCapacitacionInterna
    {
        public int ID { get; set; }
        public System.Guid FileID { get; set; }
        public string FileName { get; set; }
        public byte[] FileStreamCol { get; set; }
        public int id_capacitacion { get; set; }
    
        public virtual CapacitacionInterna CapacitacionInterna { get; set; }
    }
}
