//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembresiaConsejo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MembresiaConsejo()
        {
            this.DocumentoMembresiaConsejos = new HashSet<DocumentoMembresiaConsejo>();
            this.PersonaXMembresiaConsejos = new HashSet<PersonaXMembresiaConsejo>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public int tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoMembresiaConsejo> DocumentoMembresiaConsejos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXMembresiaConsejo> PersonaXMembresiaConsejos { get; set; }
    }
}
