//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloUtilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeloUtilidad()
        {
            this.DocumentoModeloUtilidads = new HashSet<DocumentoModeloUtilidad>();
            this.PersonaXModeloUtilidads = new HashSet<PersonaXModeloUtilidad>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string tipoModelo { get; set; }
        public string innovacionDocente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoModeloUtilidad> DocumentoModeloUtilidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXModeloUtilidad> PersonaXModeloUtilidads { get; set; }
    }
}
