//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraAdministrativaDesarrollo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraAdministrativaDesarrollo()
        {
            this.AutorXObraAdministrativaDesarrolloes = new HashSet<AutorXObraAdministrativaDesarrollo>();
            this.DocumentoObraAdministrativas = new HashSet<DocumentoObraAdministrativa>();
            this.PersonaXObraAdministrativaDesarrolloes = new HashSet<PersonaXObraAdministrativaDesarrollo>();
        }
    
        public int ID { get; set; }
        public string titulo { get; set; }
        public int numeroAutores { get; set; }
        public int id_tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraAdministrativaDesarrollo> AutorXObraAdministrativaDesarrolloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoObraAdministrativa> DocumentoObraAdministrativas { get; set; }
        public virtual TipoObraAdmi TipoObraAdmi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXObraAdministrativaDesarrollo> PersonaXObraAdministrativaDesarrolloes { get; set; }
    }
}
