//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacionDeportiva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipacionDeportiva()
        {
            this.AutorXParticipacionDeportivas = new HashSet<AutorXParticipacionDeportiva>();
            this.DocumentoParticipacionDeportivas = new HashSet<DocumentoParticipacionDeportiva>();
            this.PersonaXParticipacionDeportivas = new HashSet<PersonaXParticipacionDeportiva>();
        }
    
        public int ID { get; set; }
        public string nombreEvento { get; set; }
        public string nombreLugar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDeportiva> AutorXParticipacionDeportivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoParticipacionDeportiva> DocumentoParticipacionDeportivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionDeportiva> PersonaXParticipacionDeportivas { get; set; }
    }
}
