//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacionDestacada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipacionDestacada()
        {
            this.AutorXParticipacionDestacadas = new HashSet<AutorXParticipacionDestacada>();
            this.DocumentoParticipacionDestacadas = new HashSet<DocumentoParticipacionDestacada>();
            this.PersonaXParticipacionDestacadas = new HashSet<PersonaXParticipacionDestacada>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string anno { get; set; }
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDestacada> AutorXParticipacionDestacadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoParticipacionDestacada> DocumentoParticipacionDestacadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionDestacada> PersonaXParticipacionDestacadas { get; set; }
    }
}
