//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaXOrganizacionEvento
    {
        public int ID { get; set; }
        public int id_persona { get; set; }
        public int id_evento { get; set; }
    
        public virtual OrganizacionEvento OrganizacionEvento { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
