//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpDigital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoInvestigacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoInvestigacion()
        {
            this.AutorXProyectoInvestigacions = new HashSet<AutorXProyectoInvestigacion>();
            this.DocumentoProyectoInvestigacions = new HashSet<DocumentoProyectoInvestigacion>();
            this.PersonaXProyectoInvestigacions = new HashSet<PersonaXProyectoInvestigacion>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string medioDivulgacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXProyectoInvestigacion> AutorXProyectoInvestigacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoProyectoInvestigacion> DocumentoProyectoInvestigacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXProyectoInvestigacion> PersonaXProyectoInvestigacions { get; set; }
    }
}
